@Uinsure.Policy.API_HostAddress = http://localhost:5267/api/v1

### 201 => Make A Policy Sale
# @name createPolicy
POST {{Uinsure.Policy.API_HostAddress}}/policy
Accept: application/json
Content-Type: application/json

{
  "startDate": "{{$datetime 'yyyy-MM-dd' 5 d}}",
  "policyHolders":
  [
      {
          "firstName": "Joe",
          "lastName": "Blogs",
          "dateOfBirth": "{{$datetime 'yyyy-MM-dd' -20 y}}"
      }
  ]
}


### 200 => Get Details of a Policy
GET {{createPolicy.response.headers.Location}}
Accept: application/json